### ISSUE TITLE
Update section 5 of the libosmium manual

### ISSUE THREAD

**Issue by garaud** [osmcode/osmcode.github.io#1]
Hi,
I read http://osmcode.org/libosmium/manual.html#using-libosmium-in-your-own-projects and found 2 wrong URLs:

* the http://docs.osmcode.org/osmium-concepts-manual/ URL related to *the Libosmium concepts manual* (404)
* the reference API location http://osmcode.org/libosmium/reference/ (404)

It occurs in the file https://github.com/osmcode/osmcode.github.io/blob/master/_libosmium_manual/05_using.md

Are these URLs available elsewhere? Thank you.

Cheers,
Damien

**Comment by joto** [comment]
Thanks for the report. I have fixed the links. They are http://osmcode.org/osmium-concepts/ and http://docs.osmcode.org/libosmium/ .

**Comment by garaud** [comment]
Great! Thank you for the fix and your (great) responsiveness.
