### ISSUE TITLE
Possible Typo for tags-filter example

### ISSUE THREAD

**Issue by mapdevsaikat** [osmcode/osmcode.github.io#14]
Hi Joto,

Can you please check the [instructions added](https://docs.osmcode.org/osmium/latest/osmium-tags-filter.html) to the latest version of the 

> Matches objects of any type with the key “note”.
w/highway=primary

> Matches all ways with the key “highway” and value “primary”.
w/highway!=primary

Adding to it, when I am [following this example](https://osmcode.org/osmium-tool/manual.html#filtering-by-tags) for multiple tag filters to get the data, it is filtering out most all the listed tag added as value.

> `w/highway=motorway,trunk,primary`

The output was all highway except motorway,trunk,primary.

So, what would be the condition (`=` or `!=`) if I want to extract highways tagged in OpenStreetMap with `motorway, trunk, and primary` from a country .osm.pbf file?

**Comment by joto** [comment]
I think you are reading the examples in the wrong way, they might be a bit confusing to read. In the man pages, the explanation for each example is *after* the example expression. So `note` belongs to "Matches objects of any type with the key “note”." and `w/highway=primary` belongs to "Matches all ways with the key “highway” and value “primary”." In the [manual](https://osmcode.org/osmium-tool/manual.html#filtering-by-tags), the descriptions are above the expression examples. And yes, this is a bit confusing, sorry.

**Comment by mapdevsaikat** [comment]
Hi Joto,

Thanks for the clarification. Yes, I got confused near `note`! Thanks for the clarification. It is working fine.
