### ISSUE TITLE
Small issue in basic type.

### ISSUE THREAD

**Issue by carbsna** [osmcode/osmcode.github.io#15]
https://osmcode.org/libosmium/manual.html#basic-types
The part where it says "osmium::Location location{9300000000, 49700000000};" seems to be a error, it is over the 32bit integer limit.
Maybe it should be "{93000000, 497000000}" ?

**Comment by joto** [comment]
Thanks for the report. Those numbers were off by a factor of 100 for some reason. Fixed.
