### ISSUE TITLE
approximate info about hardware requirements would be great

### ISSUE THREAD

**Issue by matkoniecz** [osmcode/osmcode.github.io#20]
Something a bit similar to https://osm2pgsql.org/doc/manual.html#system-requirements would be really great.

> As a rule of thumb you need at least as much main memory as the PBF file with the OSM data is large. So for a planet file you currently need at least 64 GB RAM, better are 128 GB.

told me immediately that I need either a new computer or a different software. I am trying to use osmium in fact as I heard that it is less resource hungry.

I am aware of https://github.com/osmcode/pyosmium/issues/230 and I will try to make PR based on my (very inexpert) testing/measurement/benchmark. But if anyone knows any such rule of thumb, that would be great to share here (do I need 128 GB RAM or 16 GB RAM or 4 GB RAM to process planet file? Or maybe 512 GB? Or maybe osmium should not be used at such scale at all?)

And yes, obviously memory use will vary between "I want to count how many shop=* nodes are in data" or "I want to collect all tags of all objects and do this with python bindings". But some approximation like that can be made.

(I looked around docs and not seen anything hinting at this, sorry if I missed anything)

**Comment by joto** [comment]
We can always use more documentation. But I am not sure what you expect of this issue here. The osmcode.org website is about many many different things, the C++ library, the command line tool, PyOsmium, etc. and there are no simple answers to the questions you are raising. These are complex tools and you have to understand a lot of things about the structure of OSM data and all that.

**Comment by matkoniecz** [comment]
Is it impossible to give even very rough estimates of how much memory would be needed to stream through planet .pbf file? I (perhaps naively) assumed that PyOsmium and other have overhead but it would be on order of 20% rather than trippling memory/CPU use.

**Comment by joto** [comment]
If you do streaming and don't store anything, the memory use is negligable. That's the whole point of streaming. There are some buffers involved so it might be a few GB, but that's usually not something that counts. If you do streaming and store stuff it depends on what you store.

**Comment by matkoniecz** [comment]
> If you do streaming and don't store anything, the memory use is negligable. 

even when you build geometries of areas/relations? Or is it falling into "you are not streaming anymore"

**Comment by joto** [comment]
Well, then you are storing stuff of course. And it depends on what you are doing... We are going in circles. Lets stop this here.
