### ISSUE TITLE
Way-Handler-Example with WayNodes

### ISSUE THREAD

**Issue by ghost** [osmcode/osmcode.github.io#6]
Hi,

first of all, thank you for you allrounder-library!
My issue is, that the example in your manual about getting a way with its waynodes (http://osmcode.org/libosmium/manual.html#handlers) is not working, for there comes an invalid_location exception. 
Even if I surround it with an try/catch-block:

```c++
class WayNodeHandler : public osmium::handler::Handler {
public:
    void way(const osmium::Way& way) {
        for (const auto& n : way.nodes()) {
            try {
                cout << "works" << n.ref() << ": " << n.lon() << ", " << n.lat() << '\n';
            } catch (const exception& e) { 
                cout << "Nope: " << e.what() << endl;
            }
        }
    }
};
```

->

```
libc++abi.dylib: terminating with uncaught exception of type osmium::invalid_location: invalid location
Abort trap: 6
```

Am I doing something wrong?

**Comment by joto** [comment]
Okay, this is annoying. This is a copy of the stuff you added here: https://github.com/osmcode/libosmium/issues/142 and it is in the wrong repository. In the future: Please open a new issue and only one and put it in the right place, in this case https://github.com/osmcode/libosmium/issues .

**Comment by ghost** [comment]
Hi! 
Im sorry for the duplicate, i was confused, which one is the right one.
And yeah, next time i will make a new Issue at the right place - thanks for the advice and anyway: Thank you for you tip and idea! I will try that out!
