### ISSUE TITLE
Make docs pages a bit easier to find.

### ISSUE THREAD

**Issue by boblannon** [osmcode/osmcode.github.io#7]
When using the osmium tool's `help` command on a docker container, I had trouble finding docs.  This was a linux container on AWS ECS, but for some reason `man` wasn't installed, so instead of getting the manpage, I got the [fallback](https://github.com/osmcode/osmium-tool/blob/0dcfc29b194e7355c2a440b75f4da01b669059be/src/command_help.cpp#L45) message:

```
# osmium help export
osmium export: Export OSM data
You'll find more documentation at http://osmcode.org/osmium-tool/
```

I missed the links to the manpages on http://osmcode.org/osmium-tool/ because I'm lazy and didn't read closely. The links looked like they'd take me to tarballs of releases. Not sure that's really worth addressing, but take it for what it's worth.

However, it might be more helpful to get a link to the relevant manpage itself, maybe constructing the string using the name of the command and [get_osmium_version](https://github.com/osmcode/osmium-tool/blob/e8ce2a5d991af919f503426230ea762e1ee6d73f/src/version.cpp.in#L4-L6).

```
You'll find more documentation at http://docs.osmcode.org/osmium/v1.7.1/osmium-export.html
Man pages for all commands are available at http://docs.osmcode.org/osmium/v1.7.1/
General documentation at http://osmcode.org/osmium-tool/
```

/cc @springmeyer @joto

**Comment by springmeyer** [comment]
I'll let @joto comment on any doc adjustments to help things be found. As far as the `man wasn't installed`: I think in your case you were likely installing osmium-tool via mason. In this case you'll need to set up the `MANPATH` correctly to get `osmium help` working. An example is here: https://gist.github.com/springmeyer/baa0882851548ec312e9692394b47cb2

**Comment by joto** [comment]
There is more than just the man pages available on that page, so I believe linking to that page is okay.
